PetPalace/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/', include("Admin.urls")),
    path('Guest/', include("Guest.urls")),
    path('Shop/', include("Shop.urls")),
    path('User/', include("User.urls")),
    path('Hospital/', include("Hospital.urls")),
    path('Doctor/', include("Doctor.urls")),
    path('', views.home, name="home"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from Shop import views
app_name="Shop"

urlpatterns = [
    path('Home/',views.homepage,name="home"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('myprofile/',views.myprofile,name="myprofile"),
    path('changepassword/',views.changepassword,name="changepassword"),
    path('newpets/',views.newpets,name="newpets"),
    path('loadbreedtype/',views.loadbreedtype,name="load-breedtype"),
    path('delnewpets/<int:did>/',views.delete_newpets,name="delete-newpets"),
    path('newproducts/',views.newproducts,name="newproducts"),
    path('delnewproducts/<int:did>/',views.delete_newproducts,name="delete-newproducts"),
    path('newfooditem/',views.newfooditem,name="newfooditem"),
    path('deletenewfooditem/<int:did>/',views.delete_newfooditem,name="delete-newfooditem"),
    
    path('addpetstock/<int:rid>/',views.addpetstock,name="addstock-pets"),
    path('addproductstock/<int:rid>/',views.addproductstock,name="addstock-products"),
    path('addfoodstock/<int:rid>/',views.addfoodstock,name="addstock-foods"),
    path('shopviewpetbookings/',views.shopviewpetbookings,name="shopviewpetbookings"),
    path('shopviewproductbookings/',views.shopviewproductbookings,name="shopviewproductbookings"),
    path('shopviewfoodbookings/',views.shopviewfoodbookings,name="shopviewfoodbookings"),
    path('feedbackshop/',views.feedback,name="feedbackshop"),
    path('complaintshop/',views.complaint,name="complaintshop"),
    path('viewadminfeedbacks/',views.viewadminfeedbacks,name="viewadminfeedbacks"),
    path('viewadmincomplaints/',views.viewadmincomplaints,name="viewadmincomplaints"),
    path('logout/',views.logout,name="logout"),
    path('replyuser/<int:cid>/',views.replyuser,name="reply-user"),
    path('viewusercomplaints/',views.viewusercomplaints,name="UserComplaint"),
    path('viewpetreturnrequest/',views.viewpetreturnrequest,name="viewpetreturnrequest"),
    path('viewuserfeedbacks/',views.viewuserfeedbacks,name="viewuserfeedbacks"),
    
    path('replypetrequest/<int:cid>/',views.replypetrequest,name="reply-petrequest"),
    path('SetDelivery/<int:did>/',views.setDelivery,name="set-delivery"),
    path('SetDelivery1/<int:did>/',views.setDelivery1,name="set-delivery1"),
    path('SetDelivery2/<int:did>/',views.setDelivery2,name="set-delivery2")

]

User/urls.py
from User import views
from django.urls import path

app_name = "User"

urlpatterns = [
    path('Home/', views.homepage, name="home"),
    path('editprofile/', views.editprofile, name="editprofile"),
    path('myprofile/', views.myprofile, name="myprofile"),
    path('changepassword/', views.changepassword, name="changepassword"),
    path('foodsearch/', views.foodsearch, name="foodsearch"),
    path('viewmorefooditems/<int:sid>/',
         views.viewmorefooditems, name="viewmore-fooditems"),
    path('productsearch/', views.productsearch, name="productsearch"),
    path('viewmoreproductitems/<int:sid>/',
         views.viewmoreproductitems, name="viewmore-productitems"),
    path('shopsearch/', views.shopsearch, name="shopsearch"),
    path('viewpet/<int:sid>/', views.viewpet, name="viewmore-pets"),
    path('viewfood/<int:sid>/', views.viewfood, name="viewmore-foods"),
    path('viewprodduct/<int:sid>/', views.viewproduct, name="viewmore-products"),
    path('takebuypet/<int:sid>/', views.takebuypet, name="takebuypet"),
    path('takebuyproduct/<int:sid>/', views.takebuyproduct, name="takebuyproduct"),
    path('takebuyfood/<int:sid>/', views.takebuyfood, name="takebuyfood"),
    path('viewpetbookings/', views.viewpetbookings, name="viewpetbookings"),
    path('viewproductbookings/', views.viewproductbookings,
         name="viewproductbookings"),
    path('viewfoodbookings/', views.viewfoodbookings, name="viewfoodbookings"),

    path('paypets/', views.paypet, name="paypet"),
    path('payproducts/', views.payproduct, name="payproduct"),
    path('payfoods/', views.payfood, name="payfood"),
    path('paypetlater/<int:nid>/', views.paypetlater, name="paypetlater"),
    path('payproductlater/<int:nid>/',
         views.payproductlater, name="payproductlater"),
    path('payfoodlater/<int:nid>/', views.payfoodlater, name="payfoodlater"),
    path('deleteproductorder/<int:did>/',
         views.deleteproductbook, name="deleteproductorder"),
    path('deletefoodorder/<int:did>/',
         views.deletefoodbook, name="deletefoodorder"),

    path('deletepetorder/<int:did>/', views.deletepetbook, name="deletepetorder"),
    path('deleteproductorder/<int:did>/',
         views.deleteproductbook, name="deleteproductorder"),
    path('feedbackuser/', views.feedback, name="feedbackuser"),
    path('logout/', views.logout, name="logout"),
    path('usercomplaint/', views.complaint, name="usercomplaint"),
    path('hospitalsearch/', views.hospitalsearch, name="hospitalsearch"),
    path('viewdoctors/<int:sid>/', views.viewdoctor, name="viewmore-doctors"),
    path('bookdoctor/<int:sid>/', views.bookdoctor, name="bookdoctor"),
    # path('paydoctor/',views.paydoctor,name="paydoctor"),
    path('viewdoctorbookings/', views.viewdoctorbookings,
         name="viewdoctorbookings"),
    path('paydoctorlater/<int:nid>/', views.paydoctorlater, name="paydoctorlater"),
    path('deletedoctorbook/<int:did>/',
         views.deletedoctorbook, name="deletedoctorbook"),
    path('viewadminfeedbacks/', views.viewadminfeedbacks,
         name="viewadminfeedbacks"),
    path('viewadmincomplaints/', views.viewadmincomplaints,
         name="viewadmincomplaints"),
    path('complainttoshop/<int:cid>/',
         views.complainttoshop, name="complainttoshop"),
    path('returnpet/<int:aid>/', views.returnpet1, name="returnpet"),
    path('viewcomplainttoshop/', views.viewcomplainttoshop,
         name="viewcomplainttoshop"),
    path('feedbacktoshop/<int:cid>/', views.feedbacktoshop, name="feedbacktoshop"),
    path('viewfeedbacktoshop/', views.viewfeedbacktoshop,
         name="viewfeedbacktoshop"),
    path('Chat/<int:cid>/', views.chatuser, name="Chat-user"),
    path('loadchat/', views.loadchatuser, name="load-chat"),

]

User/views.py
from django.shortcuts import render, redirect
from Admin.models import BreedType, District, HospitalType, PetType, Place
from Admin.views import breedtype, hospitaltype
from django.core.mail import send_mail

from Guest.models import NewHospital, NewShop, Newuser
from Hospital.models import Newdoctor
from Shop.models import NewFoodItem, NewPets, NewProducts
from User.models import BookDoctor, BookFood, BookPet, BookProduct, Chat, complainttoshop1, complaintuser, feedbackuser, feedbackusertoshop, returnpet
from django.conf import settings

# Create your views here.


def homepage(request):
    if 'userid' in request.session:
        return render(request, 'User/Home.html')
    else:
        return redirect('Guest:login')


def editprofile(request):
    if 'userid' in request.session:
        editobj = Newuser.objects.get(id=request.session["userid"])

        if request.method == 'POST' and request.FILES:
            name = request.POST.get("name")
            contact = request.POST.get("contact")
            address = request.POST.get("address")
            photo = request.FILES.get("photo")
            editobj.name = name
            editobj.contact = contact
            editobj.address = address
            editobj.photo = photo
            editobj.save()
            return redirect('/User/Home/')
        else:
            return render(request, 'User/EditProfile.html', {"editobj": editobj})
    else:
        return redirect('Guest:login')


def changepassword(request):
    if 'userid' in request.session:
        editobj = Newuser.objects.get(id=request.session["userid"])
        if request.method == 'POST':
            curpass = request.POST.get("currentpassword")
            alpass = editobj.password
            if curpass == alpass:
                newpass = request.POST.get("newpassword")
                editobj.password = newpass
                editobj.save()
                return redirect('Guest:login')
            else:
                pass
        else:
            return render(request, 'User/ChangePassword.html')
    else:
        return redirect('Guest:login')


def myprofile(request):
    if 'userid' in request.session:
        obj1 = Newuser.objects.get(id=request.session["userid"])
        return render(request, 'User/MyProfile.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def foodsearch(request):
    if 'userid' in request.session:
        breedobj2 = PetType.objects.all()
        obj = NewFoodItem.objects.all()
        print(obj)
        if request.method == "POST":
            breedtype2 = request.POST.get("breedtype")
            breedobj = BreedType.objects.get(id=breedtype2)
            obj = NewFoodItem.objects.filter(breedtype=breedobj)
            return render(request, 'User/FoodSearch.html', {"name": obj, "dis": breedobj2})
        else:
            return render(request, 'User/FoodSearch.html', {"name": obj, "dis": breedobj2})
    else:
        return redirect('Guest:login')


def viewmorefooditems(request, sid):
    if 'userid' in request.session:
        obj1 = NewFoodItem.objects.get(id=sid)
        return render(request, 'User/ViewmoreFooDitems.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def productsearch(request):
    if 'userid' in request.session:
        breedobj2 = PetType.objects.all()
        obj = NewProducts.objects.all()
        print(obj)
        if request.method == "POST":
            breedtype2 = request.POST.get("breedtype")
            breedobj = BreedType.objects.get(id=breedtype2)
            obj = NewProducts.objects.filter(breedtype=breedobj)
            return render(request, 'User/ProductSearch.html', {"name": obj, "dis": breedobj2})
        else:
            return render(request, 'User/ProductSearch.html', {"name": obj, "dis": breedobj2})
    else:
        return redirect('Guest:login')


def viewmoreproductitems(request, sid):
    if 'userid' in request.session:
        obj1 = NewProducts.objects.get(id=sid)
        return render(request, 'User/ViewmoreProductitems.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def shopsearch(request):
    if 'userid' in request.session:
        placeobj2 = District.objects.all()
        obj = NewShop.objects.filter(vstatus=1)
        print(obj)
        if request.method == "POST":
            place2 = request.POST.get("place")
            placeobj = Place.objects.get(id=place2)
            obj = NewShop.objects.filter(place=placeobj, vstatus=1)
            return render(request, 'User/ShopwiseSearch.html', {"name": obj, "dis": placeobj2})
        else:
            return render(request, 'User/ShopWiseSearch.html', {"name": obj, "dis": placeobj2})
    else:
        return redirect('Guest:login')


def viewpet(request, sid):
    if 'userid' in request.session:
        breedobj2 = PetType.objects.all()
        obj1 = NewShop.objects.get(id=sid)
        obj = NewPets.objects.filter(shop=sid)
        print(obj)
        if request.method == "POST":
            breedtype2 = request.POST.get("breedtype")
            breedobj = BreedType.objects.get(id=breedtype2)
            obj1 = NewPets.objects.filter(breedtype=breedobj)
            return render(request, 'User/ViewPet.html', {"obj2": obj1, "dis": breedobj2})
        else:
            return render(request, 'User/ViewPet.html', {"obj2": obj, "dis": breedobj2})
    else:
        return redirect('Guest:login')


def viewfood(request, sid):
    if 'userid' in request.session:
        breedobj2 = PetType.objects.all()
        obj1 = NewShop.objects.get(id=sid)

        obj = NewFoodItem.objects.filter(shop=sid)
        print(obj)
        if request.method == "POST":
            breedtype2 = request.POST.get("breedtype")
            breedobj = BreedType.objects.get(id=breedtype2)
            obj1 = NewFoodItem.objects.filter(breedtype=breedobj)
            return render(request, 'User/ViewFood.html', {"obj2": obj1, "dis": breedobj2})
        else:
            return render(request, 'User/ViewFood.html', {"obj2": obj, "dis": breedobj2})
    else:
        return redirect('Guest:login')


def viewproduct(request, sid):
    if 'userid' in request.session:
        breedobj2 = PetType.objects.all()
        obj1 = NewShop.objects.get(id=sid)

        obj = NewProducts.objects.filter(shop=sid)
        print(obj)
        if request.method == "POST":
            breedtype2 = request.POST.get("breedtype")
            breedobj = BreedType.objects.get(id=breedtype2)
            obj1 = NewProducts.objects.filter(breedtype=breedobj)
            return render(request, 'User/ViewProduct.html', {"obj2": obj1, "dis": breedobj2})
        else:
            return render(request, 'User/ViewProduct.html', {"obj2": obj, "dis": breedobj2})
    else:
        return redirect('Guest:login')


def takebuypet(request, sid):
    if 'userid' in request.session:
        obj1 = NewPets.objects.get(id=sid)
        editobj = Newuser.objects.get(id=request.session["userid"])
        if request.method == "POST":
            totalprice = request.POST.get("totalamount")
            quantity = int(request.POST.get("quantity"))
            BookPet.objects.create(
                quantity=quantity, totalprice=totalprice, pet=obj1, user=editobj)
            curstock = int(obj1.stock)
            newstock = curstock-quantity
            obj1.stock = newstock
            obj1.save()
            return redirect("User:paypet")
        else:
            return render(request, 'User/BookPet.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def takebuyproduct(request, sid):
    if 'userid' in request.session:
        obj1 = NewProducts.objects.get(id=sid)
        editobj = Newuser.objects.get(id=request.session["userid"])
        if request.method == "POST":
            totalprice = request.POST.get("totalamount")
            quantity = int(request.POST.get("quantity"))
            BookProduct.objects.create(
                quantity=quantity, totalprice=totalprice, product=obj1, user=editobj)
            curstock = int(obj1.stock)
            newstock = curstock-quantity
            obj1.stock = newstock
            obj1.save()
            return redirect("User:payproduct")
        else:
            return render(request, 'User/BookProduct.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def takebuyfood(request, sid):
    if 'userid' in request.session:
        obj1 = NewFoodItem.objects.get(id=sid)
        editobj = Newuser.objects.get(id=request.session["userid"])
        if request.method == "POST":
            totalprice = request.POST.get("totalamount")
            quantity = int(request.POST.get("quantity"))
            BookFood.objects.create(
                quantity=quantity, totalprice=totalprice, fooditem=obj1, user=editobj)
            curstock = int(obj1.stock)
            newstock = curstock-quantity
            obj1.stock = newstock
            obj1.save()
            return redirect("User:payfood")
        else:
            return render(request, 'User/BookFood.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def paypet(request):
    if 'userid' in request.session:
        bobj = BookPet.objects.all().order_by("-id")[0]
        print(bobj)
        if request.method == "POST":
            newid = request.POST.get("txthidden")
            obj = BookPet.objects.get(id=newid)
            obj.pstatus = '1'
            email = obj.user.email
            name = obj.user.name
            send_mail(
                'Respected Sir/Madam '+name,  # subject
                "\rThank For Purchasing from petpalace.\nKindly  come to the shop and collect the pet in the next working day\n.\r\n If you have any questions and if there is anything we can improve please reply to this email. \r\n We were always happy to help!. \r\n \r\nTeam Petpalace.\n Thank You.",  # body
                settings.EMAIL_HOST_USER,
                [email],
            )
            obj.save()

User/templates/User/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    


    <a href="{% url 'User:myprofile'  %}">My Profile</a>
    
    <a href="{% url 'User:editprofile'  %}">Edit Profile</a>
    <a href="{% url 'User:changepassword'  %}">Change Password</a>
    <a href="{% url 'User:shopsearch'  %}">Shopwise Search</a>
    <a href="{% url 'User:viewpetbookings'  %}">Pet Bookings</a>
    <a href="{% url 'User:viewproductbookings'  %}">Product Bookings</a>
    <a href="{% url 'User:viewfoodbookings'  %}">Food Bookings</a>
    <a href="{% url 'User:feedbackuser'  %}">Send Admin Feedbacks</a>
    <a href="{% url 'User:usercomplaint'  %}">Send Admin Complaints</a>
    <a href="{% url 'User:viewadminfeedbacks'  %}">View Admin Feedbacks</a>
    <a href="{% url 'User:viewadmincomplaints'  %}">View Admin Complaints</a>
    <a href="{% url 'User:hospitalsearch'  %}">Hospitalwise Search</a>
    <a href="{% url 'User:viewdoctorbookings'  %}">Doctor Bookings</a>
    <a href="{% url 'User:viewcomplainttoshop'  %}">View Shop Complaints</a>
    
    <a href="{% url 'User:logout'  %}">Logout</a>
    
</body>
</html>

User/templates/User/ViewFoodBookings.html
{% extends 'User/Head.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #customers {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 50%;
        }
        
        #customers td, #customers th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #customers tr:nth-child(even){background-color: #f2f2f2;}
        
        #customers tr:hover {background-color: #ddd;}
        
        #customers th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #04AA6D;
          color: white;
        }

        #status1 {border-radius:0%;
                   background-color: lightgreen;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status2 {border-radius:0%;
                   background-color: lightskyblue;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status3 {border-radius:0%;
                   background-color: lightsteelblue;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status4 {border-radius:0%;
                   background-color: lightcyan;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status5 {border-radius:0%;
                   background-color: linen;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        </style>
</head>
<body>

    <form method="post">
               <br><br><h1 align="center">Food Bookings</h1>
        <table align="center" id="customers">
        <tr>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Shop</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Fooditemname</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Bookeddate</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Quantity</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Totalprice</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Action</td>
            <td style="padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;border: 1px solid #ddd;
padding: 8px;">Sent Complaint</td>
<td style="padding-top: 12px;
padding-bottom: 12px;
text-align: left;
background-color: #04AA6D;
color: white;border: 1px solid #ddd;
padding: 8px;">Sent Feedback</td>
<td style="padding-top: 12px;
padding-bottom: 12px;
text-align: left;
background-color: #04AA6D;
color: white;border: 1px solid #ddd;
padding: 8px;">Delivery Date</td>
            </tr>
            {% for i in obj1 %}
            <tr>
                <b><td>{{i.fooditem.shop.name}}</b></td>
                <b><td>{{i.fooditem.fooditemname}}</b></td>
              <b><td>{{i.bookeddate}}</b></td>
                <b><td>{{i.quantity}}</b></td>
                <b><td>{{i.totalprice}}</b></td>
                <b><td>{{i.deliverydate}}</b></td>

                <td>
                    
                    {% if i.pstatus == 1%}
                    <p id="status1">Already Paid</p>
                    {% else %}
                    <p id="status4"><a href="{% url 'User:payfoodlater' i.id %}">Pay Now</a></p>
                    <p id="status2"><a href="{% url 'User:deletefoodorder' i.id %}">Delete</a></p>
                    
                    
                    {% endif %}
                </td>
                <td>
                    <p id="status5"><a href="{% url 'User:complainttoshop' i.id %}">Sent Complaint</a></p>
                </td>
                <td>
                    <p id="status3"><a text="black" href="{% url 'User:feedbacktoshop' i.id %}">Feedback</a></p>
                    <!----  <p><a href="{% url 'User:returnpet' i.id %}">Return</a></p>-->
                    
                </td>
            </tr>
            {% endfor %}

        </table>

</body>
</html>


{% endblock  %}

User/templates/User/ViewPetBookings.html
{% extends 'User/Head.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #customers {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 50%;
        }
        
        #customers td, #customers th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #customers tr:nth-child(even){background-color: #f2f2f2;}
        
        #customers tr:hover {background-color: #ddd;}
        
        #customers th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #04AA6D;
          color: white;
        }

        #status1 {border-radius:0%;
                   background-color: lightgreen;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status2 {border-radius:0%;
                   background-color: lightskyblue;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status3 {border-radius:0%;
                   background-color: lightsteelblue;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status4 {border-radius:0%;
                   background-color: lightcyan;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        #status5 {border-radius:0%;
                   background-color: linen;
                     padding: 0.2rem 1rem;
                     text-align: center;
        }
        </style>
</head>
<body>
    <form method="post">
        <br><br>
        <h1 align="center">Pet Booking</h1>
        <table align="center" id="customers" >
                
            <tr>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Shop</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Pettype</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Breedtype</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Bookeddate</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Quantity</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Totalprice</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Action</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Sent Complaint</td>
                <td style="padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;border: 1px solid #ddd;
  padding: 8px;">Sent Feedback</td>
  <td style="padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;border: 1px solid #ddd;
padding: 8px;">Delivery Date</td>
                </tr>
            {% for i in obj1 %}
                
                <tr>
                    <td>{{i.pet.shop.name}}</td>
                    <td>{{i.pet.breedtype.pettype.pettype}}</td>
                    <td>{{i.pet.breedtype.breedtype}}</td>
                    <td>{{i.bookeddate}}</td>
                    <td>{{i.quantity}}</td>
                    <td>{{i.totalprice}}</td>
                    <td>{{i.deliverydate}}</td>

                    <td>
                        {% if i.pstatus == 1%}
                        <p id="status1">Already Paid</p>
                        {% else %}
                        <p id="status4"><a href="{% url 'User:paypetlater' i.id %}">Pay Now</a></p>
                        <p id="status5"><a href="{% url 'User:deletepetorder' i.id %}">Delete</a></p>

                        {% endif %}
                    </td>
                    <td>
                        <p id="status2"><a href="{% url 'User:complainttoshop' i.id %}">Complaint</a></p>
                        <!----  <p><a href="{% url 'User:returnpet' i.id %}">Return</a></p>-->
                        
                    </td>
                
                
                <td>
                    <p id="status3"><a text="black" href="{% url 'User:feedbacktoshop' i.id %}">Feedback</a></p>
                    <!----  <p><a href="{% url 'User:returnpet' i.id %}">Return</a></p>-->
                    
                </td>
            </tr>
                {% endfor %}
        </table>
        </form>
</body>
</html>


{% endblock  %}