Doctor/urls.py
from Doctor import views
from django.urls import path

app_name = "Doctor"

urlpatterns = [
    path('Home/', views.homepage, name="home"),
    path('editprofile/', views.editprofile, name="editprofile"),
    path('myprofile/', views.myprofile, name="myprofile"),
    path('changepassword/', views.changepassword, name="changepassword"),
    path('feedbackdoctor/', views.feedback, name="feedbackdoctor"),
    path('complaintdoctor/', views.complaint, name="complaintdoctor"),
    path('viewadminfeedbacks/', views.viewadminfeedbacks,
         name="viewadminfeedbacks"),
    path('viewadmincomplaints/', views.viewadmincomplaints,
         name="viewadmincomplaints"),
    path('logout/', views.logout, name="logout"),
    path('viewdoctorbooking/', views.viewdoctorbooking, name="viewdoctorbooking"),
    path('acceptdoctor/<int:aid>/', views.acceptdoctor, name="accept-user"),
    path('rejectdoctor/<int:rid>/', views.rejectdoctor, name="reject-user"),
    path('acceptedbookings/', views.acceptedbookings, name="acceptedbookings"),
    path('Chat/<int:cid>/', views.chat, name="Chat-doctor"),
    path('loadchat/', views.loadchat, name="load-chat"),


]

Guest/urls.py
from django.urls import path

from Guest import views

app_name = "Guest"

urlpatterns = [
    path('newuser/', views.newuser, name="newuser"),
    path('loadplace/', views.loadplace, name="load-place"),
    path('newshop/', views.newshop, name="newshop"),
    path('newhospital/', views.newhospital, name="newhospital"),
    path('login/', views.Login, name="login"),
    path('newaccount/', views.newaccount, name="newaccount"),

    path('forgotpassword/', views.forgotpassword, name="forgotpassword"),





]

Hospital/urls.py
from django.urls import path
from Hospital import views
app_name="Hospital"

urlpatterns = [
    
    path('Home/',views.homepage,name="home"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('myprofile/',views.myprofile,name="myprofile"),
    path('changepassword/',views.changepassword,name="changepassword"),
    
    path('newdoctor/',views.newdoctor,name="newdoctor"),
    path('viewdoctors/',views.viewdoctors,name="viewdoctors"),

    path('deldoctor/<int:did>/',views.delete_doctor,name="DeleteDoctor"),
    path('feedbackhospital/',views.feedback,name="feedbackhospital"),
    path('complainthospital/',views.complaint,name="complainthospital"),
    path('viewadminfeedbacks/',views.viewadminfeedbacks,name="viewadminfeedbacks"),
    path('logout/',views.logout,name="logout"),
    path('viewadmincomplaints/',views.viewadmincomplaints,name="viewadmincomplaints"),
    path('viewdoctorbookings/',views.viewdoctorbookings,name="viewdoctorbookings"),

    
    

]

PetPalace/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/', include("Admin.urls")),
    path('Guest/', include("Guest.urls")),
    path('Shop/', include("Shop.urls")),
    path('User/', include("User.urls")),
    path('Hospital/', include("Hospital.urls")),
    path('Doctor/', include("Doctor.urls")),
    path('', views.home, name="home"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from Shop import views
app_name="Shop"

urlpatterns = [
    path('Home/',views.homepage,name="home"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('myprofile/',views.myprofile,name="myprofile"),
    path('changepassword/',views.changepassword,name="changepassword"),
    path('newpets/',views.newpets,name="newpets"),
    path('loadbreedtype/',views.loadbreedtype,name="load-breedtype"),
    path('delnewpets/<int:did>/',views.delete_newpets,name="delete-newpets"),
    path('newproducts/',views.newproducts,name="newproducts"),
    path('delnewproducts/<int:did>/',views.delete_newproducts,name="delete-newproducts"),
    path('newfooditem/',views.newfooditem,name="newfooditem"),
    path('deletenewfooditem/<int:did>/',views.delete_newfooditem,name="delete-newfooditem"),
    
    path('addpetstock/<int:rid>/',views.addpetstock,name="addstock-pets"),
    path('addproductstock/<int:rid>/',views.addproductstock,name="addstock-products"),
    path('addfoodstock/<int:rid>/',views.addfoodstock,name="addstock-foods"),
    path('shopviewpetbookings/',views.shopviewpetbookings,name="shopviewpetbookings"),
    path('shopviewproductbookings/',views.shopviewproductbookings,name="shopviewproductbookings"),
    path('shopviewfoodbookings/',views.shopviewfoodbookings,name="shopviewfoodbookings"),
    path('feedbackshop/',views.feedback,name="feedbackshop"),
    path('complaintshop/',views.complaint,name="complaintshop"),
    path('viewadminfeedbacks/',views.viewadminfeedbacks,name="viewadminfeedbacks"),
    path('viewadmincomplaints/',views.viewadmincomplaints,name="viewadmincomplaints"),
    path('logout/',views.logout,name="logout"),
    path('replyuser/<int:cid>/',views.replyuser,name="reply-user"),
    path('viewusercomplaints/',views.viewusercomplaints,name="UserComplaint"),
    path('viewpetreturnrequest/',views.viewpetreturnrequest,name="viewpetreturnrequest"),
    path('viewuserfeedbacks/',views.viewuserfeedbacks,name="viewuserfeedbacks"),
    
    path('replypetrequest/<int:cid>/',views.replypetrequest,name="reply-petrequest"),
    path('SetDelivery/<int:did>/',views.setDelivery,name="set-delivery"),
    path('SetDelivery1/<int:did>/',views.setDelivery1,name="set-delivery1"),
    path('SetDelivery2/<int:did>/',views.setDelivery2,name="set-delivery2")

]

Doctor/models.py
from django.db import models

from Hospital.models import Newdoctor

# Create your models here.
class feedbackdoctor(models.Model):
    feedback=models.TextField(max_length=50)
    doctor=models.ForeignKey(Newdoctor,on_delete=models.CASCADE)
    doj=models.DateField(auto_now_add=True)

class complaintdoctor(models.Model):
    complainttitle=models.CharField(max_length=50)
    content=models.TextField(max_length=50)
    doctor=models.ForeignKey(Newdoctor,on_delete=models.CASCADE)
    attachment=models.FileField(null=True,upload_to='Uploads/attachmentdoctor/')
    reply=models.TextField(null=True,max_length=50,default="noreply")
    doj=models.DateField(auto_now_add=True)
    status=models.IntegerField(default=False)

Hospital/models.py
from django.db import models

from Admin.models import Place
from Guest.models import NewHospital

# Create your models here.

class Newdoctor(models.Model):
    name=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    email=models.EmailField(unique=True, max_length=50)
    address=models.TextField(max_length=50)
    place=models.ForeignKey(Place,on_delete=models.CASCADE)
    photo=models.FileField(upload_to='Uploads/newdoctorphotos/')
    proof=models.FileField(upload_to='Uploads/newdoctorphotos/')
    qualification=models.CharField(max_length=50,null=True)
    password=models.CharField(max_length=50)
    doj=models.DateField(auto_now_add=True)
    hospital=models.ForeignKey(NewHospital,on_delete=models.CASCADE)

class feedbackhospital(models.Model):
    feedback=models.TextField(max_length=50)
    hospital=models.ForeignKey(NewHospital,on_delete=models.CASCADE)
    doj=models.DateField(auto_now_add=True)


class complainthospital(models.Model):
    complainttitle=models.CharField(max_length=50)
    content=models.TextField(max_length=50)
    hospital=models.ForeignKey(NewHospital,on_delete=models.CASCADE)
    attachment=models.FileField(null=True,upload_to='Uploads/attachmenthospital/')
    reply=models.TextField(null=True,max_length=50,default="noreply")
    doj=models.DateField(auto_now_add=True)
    status=models.IntegerField(default=False)
    

Doctor/views.py
from django.shortcuts import render, redirect
from Doctor.models import complaintdoctor, feedbackdoctor

from Guest.models import NewHospital, Newuser
from Hospital.models import Newdoctor
from User.models import BookDoctor, Chat
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def homepage(request):
    if 'doctorid' in request.session:

        return render(request, 'Doctor/Home.html')
    else:
        return redirect('Guest:login')


def editprofile(request):
    if 'doctorid' in request.session:

        viewobj1 = Newdoctor.objects.get(id=request.session["doctorid"])

        if request.method == 'POST' and request.FILES:
            name = request.POST.get("name")
            contact = request.POST.get("contact")

            address = request.POST.get("address")
            photo = request.FILES.get("photo")

            viewobj1.name = name
            viewobj1.contact = contact

            viewobj1.address = address
            viewobj1.photo = photo

            viewobj1.save()
            return redirect('/Doctor/Home/')
        else:
            return render(request, 'Doctor/EditProfile.html', {"editobj": viewobj1})
    else:
        return redirect('Guest:login')


def changepassword(request):
    if 'doctorid' in request.session:

        editobj = Newdoctor.objects.get(id=request.session["doctorid"])

        if request.method == 'POST':
            curpass = request.POST.get("currentpassword")
            alpass = editobj.password
            if curpass == alpass:
                newpass = request.POST.get("newpassword")
                editobj.password = newpass
                editobj.save()
                return redirect('Guest:login')
        else:
            return render(request, 'Doctor/ChangePassword.html')
    else:
        return redirect('Guest:login')


def myprofile(request):
    if 'doctorid' in request.session:

        obj1 = Newdoctor.objects.get(id=request.session["doctorid"])

        return render(request, 'Doctor/MyProfile.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def feedback(request):
    if 'doctorid' in request.session:

        editobj = Newdoctor.objects.get(id=request.session["doctorid"])
        if request.method == "POST":
            feedback = request.POST.get("feedback")
            feedbackdoctor.objects.create(feedback=feedback, doctor=editobj)
            return redirect('/Doctor/Home/')

        else:
            return render(request, 'Doctor/Feedbackdoctor.html')
    else:
        return redirect('Guest:login')


def complaint(request):
    if 'doctorid' in request.session:
        editobj = Newdoctor.objects.get(id=request.session["doctorid"])
        if request.method == "POST" and request.FILES:
            complainttitle = request.POST.get("complainttitle")
            content = request.POST.get("content")
            attachment = request.FILES.get("attachment")
            complaintdoctor.objects.create(
                complainttitle=complainttitle, content=content, doctor=editobj, attachment=attachment)
            return redirect('/Doctor/Home/')
        else:
            return render(request, 'Doctor/DoctorComplaint.html')
    else:
        return redirect('Guest:login')


def logout(request):
    if 'doctorid' in request.session:
        del request.session['doctorid']
        return redirect('Guest:login')
    else:
        return redirect('Guest:login')


def viewadminfeedbacks(request):
    if 'doctorid' in request.session:
        obj1 = feedbackdoctor.objects.all()
        return render(request, 'Doctor/ViewAdminFeedbacks.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def viewadmincomplaints(request):
    if 'doctorid' in request.session:
        obj1 = complaintdoctor.objects.all()
        return render(request, 'Doctor/ViewAdminComplaints.html', {"obj1": obj1})
    else:
        return redirect('Guest:login')


def viewdoctorbooking(request):
    if 'doctorid' in request.session:
        doctorobj = Newdoctor.objects.get(id=request.session["doctorid"])
        dobj = BookDoctor.objects.filter(doctor=doctorobj)
        return render(request, 'Doctor/ViewBookings.html', {"dobj": dobj})
    else:
        return redirect('Guest:login')


def acceptdoctor(request, aid):
    if 'doctorid' in request.session:
        userobj = BookDoctor.objects.get(id=aid)
        doctor = userobj.doctor.name
        name = userobj.user.name
        email1 = userobj.user.email
        userobj.vstatus = '1'
        send_mail(
            'Respected Sir/Madam '+name,  # subject
            "\rYour appointment for consulting Dr."+doctor + \
            " is successful.He will contact you soon. \r\n \r\n From Team Petpalace.\n Thank You.",  # body
            settings.EMAIL_HOST_USER,
            [email1],
        )
        userobj.save()
        return redirect('Doctor:viewdoctorbooking')
    else:
        return redirect('Guest:login')


def rejectdoctor(request, rid):
    if 'doctorid' in request.session:
        userobj = BookDoctor.objects.get(id=rid)
        doctor = userobj.doctor.name
        name = userobj.user.name
        email1 = userobj.user.email
        userobj.vstatus = '2'
        send_mail(
            'Respected Sir/Madam ' + name,  # subject
            "\r Your appointment for consulting dr."+doctor + \
            " is resheduled.Please take new appointment for consulting the doctor. \r\n \r\nThis is from Team Petpalace.\n Thank You.",  # body
            settings.EMAIL_HOST_USER,
            [email1],
        )
        userobj.save()
        return redirect('Doctor:viewdoctorbooking')
    else:
        return redirect('Guest:login')


def acceptedbookings(request):
    if 'doctorid' in request.session:
        hosobj = BookDoctor.objects.filter(vstatus=1)
        return render(request, 'Doctor/AcceptBookings.html', {"hosobj": hosobj})
    else:
        return redirect('Guest:login')


def chat(request, cid):
    chatobj = BookDoctor.objects.get(id=cid)
    if request.method == "POST":
        cied = request.POST.get("cid")
        # print(cied)
        ciedobj = Newuser.objects.get(id=cied)
        sobj = Newdoctor.objects.get(id=request.session["doctorid"])
        content = request.POST.get("msg")
        # print(cied)
        print(content)
        Chat.objects.create(
            from_doctor=sobj, to_user=ciedobj, content=content, from_user=None, to_doctor=None)
        return render(request, 'Doctor/Chat.html', {"chatobj": chatobj})
    else:
        return render(request, 'Doctor/Chat.html', {"chatobj": chatobj})


def loadchat(request):
    cid = request.GET.get("cid")
    request.session["cid"] = cid

    cid1 = request.session["cid"]
    # print(cid1)

    # print(cid)
    shopobj = Newuser.objects.get(id=cid)
    # print(userobj)
    sid = request.session["doctorid"]
    # print(sid)
    suserobj = Newdoctor.objects.get(id=request.session["doctorid"])
    # chatobj1 = Chat.objects.filter(Q(to_user=suserobj) | Q(
    #     from_user=suserobj), Q(to_shop=shopobj) | Q(from_shop=shopobj))
    # print(chatobj1)  # send message

    # print(chatobj2)  # recived msg
    chatobj = Chat.objects.raw(
        "select * from User_chat c inner join Hospital_newdoctor u on (u.id=c.from_doctor_id) or (u.id=c.to_doctor_id) WHERE  c.from_user_id=%s or c.to_user_id=%s order by c.date", params=[(cid1), (cid1)])

    print(chatobj.query)

    return render(request, 'Doctor/Load.html', {"obj": chatobj, "sid": sid, "shop": shopobj, "userobj": suserobj})

Hospital/templates/Hospital/Head.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>PetLover - Pet Care Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'temp1/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="{% static 'temp1/lib/flaticon/font/flaticon.css' %}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'temp1/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'temp1/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'temp1/css/style.css' %}" rel="stylesheet">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'form.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-lg-5">
            <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white pr-3" href="">FAQs</a>
                    <span class="text-white">|</span>
                    <a class="text-white px-3" href="">Help</a>
                    <span class="text-white">|</span>
                    <a class="text-white pl-3" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-3" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-3" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-3" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row py-3 px-lg-5">
            <div class="col-lg-4">
                <a href="" class="navbar-brand d-none d-lg-block">
                    <h1 class="m-0 display-5 text-capitalize"><span class="text-primary">Pet</span>Lover</h1>
                </a>
            </div>
            <div class="col-lg-8 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="d-inline-flex flex-column text-center pr-3 border-right">
                        <h6>Opening Hours</h6>
                        <p class="m-0">10.00AM - 5.00PM</p>
                    </div>
                    <div class="d-inline-flex flex-column text-center px-3 border-right">
                        <h6>Email Us</h6>
                        <p class="m-0">petpalace@gmail.com</p>
                    </div>
                    <div class="d-inline-flex flex-column text-center pl-3">
                        <h6>Call Us</h6>
                        <p class="m-0">9645735893</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-lg-5">
            <a href="" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-5 text-capitalize font-italic text-white"><span class="text-primary">Safety</span>First</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{% url 'Hospital:home' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'Hospital:viewdoctorbookings' %}" class="nav-item nav-link active">Bookings</a>

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Doctors</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'Hospital:newdoctor'  %}" class="dropdown-item">Add</a>
                            <a href="{% url 'Hospital:viewdoctors'  %}" class="dropdown-item">View</a>
                
                            

                        </div>
                    </div>
            
                   
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Feedbacks and Complains</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'Hospital:feedbackhospital' %}" class="dropdown-item">Site Feedback</a>
                            <a href="{% url 'Hospital:complainthospital' %}" class="dropdown-item">Site Complaint</a>
                           <a href="{% url 'Hospital:viewadminfeedbacks' %}" class="dropdown-item">View Site Feedbacks</a>
                            <a href="{% url 'Hospital:viewadmincomplaints' %}" class="dropdown-item">View Site Complaints</a>
                            
                        </div>
                    </div>
                    
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Privacy</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'Hospital:myprofile' %}" class="dropdown-item">My Profile</a>
                            <a href="{% url 'Hospital:editprofile' %}" class="dropdown-item">Edit Profile</a>
                            <a href="{% url 'Hospital:changepassword' %}" class="dropdown-item">Change Password</a>

                        </div>
                    </div>
                    <a href="{% url 'Hospital:logout'  %}" class="nav-item nav-link">Logout</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    {% block content %}



    {% endblock %}

    
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white mt-5 py-5 px-sm-3 px-md-5">
      <div class="row pt-5">
          <div class="col-lg-4 col-md-12 mb-5">
              <h1 class="mb-3 display-5 text-capitalize text-white"><span class="text-primary">Pet</span>Palace</h1>
              <p class="m-0">Pet Palace is a premium website for buying exclusively high breed pets directly from pet shops around kerala.</p>
          </div>
          <div class="col-lg-8 col-md-12">
              <div class="row">
                  <div class="col-md-4 mb-5">
                      <h5 class="text-primary mb-4">Get In Touch</h5>
                      <p><i class="fa fa-map-marker-alt mr-2"></i>Pet Palace,Kochi,Kerala</p>
                      <p><i class="fa fa-phone-alt mr-2"></i>9645735893</p>
                      <p><i class="fa fa-envelope mr-2"></i>petpalace@gmail.com</p>
                      <div class="d-flex justify-content-start mt-4">
                          <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 36px; height: 36px;" href="#"><i class="fab fa-twitter"></i></a>
                          <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 36px; height: 36px;" href="#"><i class="fab fa-facebook-f"></i></a>
                          <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 36px; height: 36px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                          <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 36px; height: 36px;" href="#"><i class="fab fa-instagram"></i></a>
                      </div>
                  </div>
                  <div class="col-md-4 mb-5">
                      <h5 class="text-primary mb-4">Popular Links</h5>
                      <div class="d-flex flex-column justify-content-start">
                          <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                          <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                          <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                          <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Team</a>
                          <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                      </div>
                  </div>
                  <div class="col-md-4 mb-5">
                      <h5 class="text-primary mb-4">Newsletter</h5>
                      <form action="">
                          <div class="form-group">
                              <input type="text" class="form-control border-0" placeholder="Your Name" required="required" />
                          </div>
                          <div class="form-group">
                              <input type="email" class="form-control border-0" placeholder="Your Email" required="required" />
                          </div>
                          <div>
                              <button class="btn btn-lg btn-primary btn-block border-0" type="submit">Submit Now</button>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <div class="container-fluid text-white py-4 px-sm-3 px-md-5" style="background: #111111;">
      <div class="row">
          <div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
              <p class="m-0 text-white">
                  &copy; <a class="text-white font-weight-bold" href="#">Pet Palace</a>. All Rights Reserved. Designed by
                  <a class="text-white font-weight-bold" href="https://htmlcodex.com">Team Pet Palace</a>
              </p>
          </div>
          <div class="col-md-6 text-center text-md-right">
              <ul class="nav d-inline-flex">
                  <li class="nav-item">
                      <a class="nav-link text-white py-0" href="#">Privacy</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link text-white py-0" href="#">Terms</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link text-white py-0" href="#">FAQs</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link text-white py-0" href="#">Help</a>
                  </li>
              </ul>
          </div>
      </div>
  </div>
  <!-- Footer End -->


  <!-- Back to Top -->
  <a href="#" class="btn btn-lg btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


  <!-- JavaScript Libraries -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'temp1/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'temp1/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'temp1/lib/tempusdominus/js/moment.min.js' %}"></script>
  <script src="{% static 'temp1/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
  <script src="{% static 'temp1/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

  <!-- Contact Javascript File -->
  <script src="{% static 'temp1/mail/jqBootstrapValidation.min.js' %}"></script>
  <script src="{% static 'temp1/mail/contact.js' %}"></script>

  <!-- Template Javascript -->
  <script src="{% static 'temp1/js/main.js' %}"></script>
</body>

</html>